# Generated by Django 5.1.1 on 2024-09-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(choices=[('2Б', '2Б'), ('3Б', '3Б'), ('2А', '2А'), ('1Б', '1Б'), ('1А', '1А'), ('3А', '3А')], default='1А', max_length=2, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(choices=[('2Б', '2Б'), ('3Б', '3Б'), ('2А', '2А'), ('1Б', '1Б'), ('1А', '1А'), ('3А', '3А')], default='1А', max_length=2, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(choices=[('2Б', '2Б'), ('3Б', '3Б'), ('2А', '2А'), ('1Б', '1Б'), ('1А', '1А'), ('3А', '3А')], default='1А', max_length=2, verbose_name='Лето'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(choices=[('2Б', '2Б'), ('3Б', '3Б'), ('2А', '2А'), ('1Б', '1Б'), ('1А', '1А'), ('3А', '3А')], default='1А', max_length=2, verbose_name='Зима'),
        ),
    ]
